GET http://localhost:3000/todos?status=HIGH

###

GET http://localhost:3000/todos/1

###

GET http://localhost:3000/agenda?date=2021-4-f

###

POST http://localhost:3000/todos/
Content-Type: application/json

{
 "id": 8,
 "todo": "Learn Node JS",
 "priority": "HIGH",
 "status": "IN PROGRESS",
 "category": "LEARNING",
 "dueDate": "2021-03-13"
}

###

PUT http://localhost:3000/todos/1
Content-Type: application/json

{
 "category": "HOME"
}

###

DELETE http://localhost:3000/todos/6
